-- 코드를 입력하세요
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME FROM ANIMAL_OUTS
    WHERE ANIMAL_OUTS.ANIMAL_ID NOT IN (
        SELECT ANIMAL_INS.ANIMAL_ID FROM ANIMAL_INS, ANIMAL_OUTS
        WHERE ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
    )
    ORDER BY ANIMAL_ID;